name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::program"
      - name: Echo a secret  
        run: echo "programming is fun, but my most productive days are those in which I am not developing any programs."