name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::program"
      - name: echo a secret  
        run: echo "programming is great, but my most productive days are those when I do not write a program."
