name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::test"
      - name: Echo a secret  
        run: echo "this is a test and am testing TESTing TestTing test-ing est things"